FROM alpine:3.14

RUN  apk update \
  && apk upgrade \
  && apk add --update openjdk11 tzdata curl unzip bash \
  && rm -rf /var/cache/apk/*

RUN addgroup -S notes && adduser -S notes -G notes

USER notes:notes

ARG JAR_FILE=*.jar

COPY ${JAR_FILE} easy-note.jar

COPY application.properties application.properties

ENTRYPOINT ["java", "-jar", "/easy-note.jar"]