FROM maven:3.5-jdk-11 as buildstage

RUN mkdir /opt/notes

WORKDIR /opt/notes

RUN git clone https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git /opt/notes

RUN mvn package -Dmaven.test.skip=true



FROM alpine:3.14

RUN  apk update \
  && apk upgrade \
  && apk add --update openjdk11 tzdata curl unzip bash \
  && rm -rf /var/cache/apk/*

RUN addgroup -S notes && adduser -S notes -G notes

RUN mkdir /opt/notes

RUN chown -R notes:notes /opt/notes

USER notes:notes

WORKDIR /opt/notes

COPY --from=buildstage /opt/notes/target/easy-notes-1.0.0.jar .

COPY application.properties application.properties

ENTRYPOINT ["java", "-jar", "/opt/notes/easy-note.jar"]

